//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadParcial2Ydzn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serie
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string sinopsis { get; set; }
        public string director { get; set; }
        public Nullable<int> episodios { get; set; }
        public Nullable<System.DateTime> fechaEstreno { get; set; }
        public Nullable<short> estado { get; set; }
        public string urlTrailer { get; set; }
        public string idiomaOriginal { get; set; }
    }
}
